### ISSUE TITLE
parameter count not working 

### ISSUE THREAD

**Issue by brucefeiwang** [jdtrat/chimpr#5]
```r
list <- ChmpList$new(conn, count = 10,id = "*****")

```
Error in .subset2(public_bind_env, "initialize")(...) : 
  unused argument (count = 10)
</details>

**Comment by sckott** [comment]
thanks for the issue. sorry the error isn' tthe most useful, but it does correctly state that you've used an unused argument, meaning `$new()` doesn't accept that arg

are you familiar with [R6 classes](https://cloud.r-project.org/web/packages/R6/)?

We use those in this package. the `$new()` method on each class accepts only certain parameters to initialize the classs, and then methods on the class accept a different set of parameters, although they can share parameters too. 

Here's the docs for chimpr: https://sckott.github.io/chimpr/ 

The docs for `ChmpList` https://sckott.github.io/chimpr/reference/ChmpList.html - The `$new()` method accepts the params `conn` and `id`. The `count` param can be passed to some of the methods

**Comment by brucefeiwang** [comment]
Thanks!
